apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8sforcvs-2d3b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8sforcvs-2d3b"
  template:
    metadata:
      labels:
        app: "k8sforcvs-2d3b"
    spec:
      containers:
        - name: "k8sforcvs-2d3b"
          image: "crforpoc.azurecr.io/k8sforcvs"
          ports:
          - containerPort: 80