on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crforpoc.azurecr.io
        username: ${{ secrets.acr_crforpoc_username }}
        password: ${{ secrets.acr_crforpoc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crforpoc.azurecr.io/k8sforcvs:${{ github.sha }}
        docker push crforpoc.azurecr.io/k8sforcvs:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sforcvs_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep simpleapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace simpleapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: simpleapp
        container-registry-url: crforpoc.azurecr.io
        container-registry-username: ${{ secrets.acr_crforpoc_username }}
        container-registry-password: ${{ secrets.acr_crforpoc_password }}
        secret-name: k8sforcvsdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: simpleapp
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          crforpoc.azurecr.io/k8sforcvs:${{ github.sha }}
        imagepullsecrets: |
          k8sforcvsdockerauth